// front-vue/src/components/Footer.vue
<template>
  <div class="row">
    <hr>
      <footer>
        <p class="float-xs-right">
          {{ $t('lang-bar.other') }}:
          <button v-on:click="swtichLang(l)" v-for="l in info.languages" class="btn btn-link btn-sm">
            {{ $t(`languages.${l}`) }}
          </button>
        </p>
        <p>
          &copy; {{ info.copyright }}
          &middot; <a href="#">Privacy</a>
          &middot; <a href="#">Terms</a>
        </p>
      </footer>
  </div>
</template>

<script>
import {swtichLang} from '../i18n'
import actions from '../engines/actions'

export default {
  name: 'layout-footer',
  computed: {
    info () {
      return this.$store.state.siteInfo
    }
  },
  methods: {
    swtichLang
  },
  created () {
    if (!this.$store.state.siteInfo.copyright) {
      this.$store.commit(actions.auth.refreshLayout)
    }
  }
}
</script>

// front-react/app-old/components/Footer.jsx
import React, { PropTypes } from 'react'
import { translate } from 'react-i18next'
import { connect } from 'react-redux'

import {get} from '../ajax'
import {refresh} from '../engines/auth/actions'

const Widget = React.createClass({
  componentDidMount () {
    const {onRefresh} = this.props
    onRefresh()
  },
  render () {
    const {t, info} = this.props

    var links = info.bottomLinks ? info.bottomLinks.map(function (l, i) {
      return (
        <span key={i}>
          &middot;
          <a href={l.href}> {l.label} </a>
        </span>
      )
    }) : <span/>

    return (
      <div className="row">
        <hr/>
        <footer>
          <p className="pull-right">
            {t('lang-bar.other')}
            <a href="/?locale=en-US"> {t('languages.english')} </a>
            <a href="/?locale=zh-CN"> {t('languages.simplified-chinese')} </a>
            <a href="/?locale=zh-TW"> {t('languages.traditional-chinese')} </a>
          </p>
          <p>
            &copy; {info.copyright}
            { links }
          </p>
        </footer>
      </div>
    )
  }
})

Widget.propTypes = {
  t: PropTypes.func.isRequired,
  info: PropTypes.object.isRequired,
  onRefresh: PropTypes.func.isRequired
}

const Model = connect(
  state => ({info: state.siteInfo}),
  dispatch => ({
    onRefresh: function () {
      get('/layout', function (ifo) {
        dispatch(refresh(ifo))
        document.documentElement.lang = ifo.lang
        document.title = ifo.title
      })
    }
  })
)(Widget)

export default translate()(Model)
