// front-vue/src/components/PersonalBar.vue
<template>
  <li v-if="user.uid" class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" :id="bar_id" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{ $t('auth.pages.welcome', {name: user.sub}) }}
    </a>
    <div class="dropdown-menu dropdown-menu-right" :aria-labelledby="bar_id">
      <router-link class="dropdown-item" :to="{ name: 'dashboard' }">
        {{ $t('auth.pages.dashboard') }}
      </router-link>
      <a v-on:click="signOut()" class="dropdown-item">{{ $t('auth.pages.sign-out') }}</a>
    </div>
  </li>
  <li v-else class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" :id="bar_id" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{ $t('auth.pages.sign-in-or-up') }}
    </a>
    <div class="dropdown-menu dropdown-menu-right" :aria-labelledby="bar_id">
      <router-link v-for="l in non_sign_in" class="dropdown-item" :to="{ name: `users.${l}` }">
        {{ $t(`auth.pages.${l}`) }}
      </router-link>
    </div>
  </li>
</template>

<script>
import actions from '../engines/actions'

export default {
  name: 'forgot-password',
  data () {
    return {
      bar_id: 'personal-bar',
      non_sign_in: [
        'sign-in',
        'sign-up',
        'forgot-password',
        'confirm',
        'unlock'
      ]
    }
  },
  computed: {
    user () {
      return this.$store.state.currentUser
    }
  },
  methods: {
    signOut () {
      this.$router.push({name: 'usres.sign-in'})
      this.$store.commit(actions.auth.signOut)
    }
  },
  created () {
    if (!this.$store.state.currentUser.uid) {
      this.$store.commit(
        actions.auth.signIn,
        window.sessionStorage.getItem('token')
      )
    }
  }
}
</script>

// front-react/app-old/components/PersonalBar.jsx
import React, { PropTypes } from 'react'
import { connect } from 'react-redux'
import { translate } from 'react-i18next'
import {NavDropdown, MenuItem} from 'react-bootstrap'
import {LinkContainer} from 'react-router-bootstrap'

import {signIn, signOut} from '../engines/auth/actions'
import {isEmpty} from '../engines/auth/utils'

const Widget = React.createClass({
  componentDidMount () {
    const {onLoad} = this.props
    onLoad()
  },
  render () {
    const {t, user, onSignOut} = this.props
    return isEmpty(user) ? (
    <NavDropdown eventKey={4} title={t('auth.pages.sign-in-or-up')} id="personal-bar">
      <LinkContainer to={{pathname: '/users/sign-in'}}>
        <MenuItem eventKey={4.1}>{t('auth.pages.sign-in')}</MenuItem>
      </LinkContainer>
      <LinkContainer to={{pathname: '/users/sign-up'}}>
        <MenuItem eventKey={4.2}>{t('auth.pages.sign-up')}</MenuItem>
      </LinkContainer>
      <MenuItem divider />
      <LinkContainer to={{pathname: '/users/forgot-password'}}>
        <MenuItem eventKey={4.2}>{t('auth.pages.forgot-password')}</MenuItem>
      </LinkContainer>
      <LinkContainer to={{pathname: '/users/confirm'}}>
        <MenuItem eventKey={4.2}>{t('auth.pages.confirm')}</MenuItem>
      </LinkContainer>
      <LinkContainer to={{pathname: '/users/unlock'}}>
        <MenuItem eventKey={4.2}>{t('auth.pages.unlock')}</MenuItem>
      </LinkContainer>
    </NavDropdown>
    ) : (
      <NavDropdown eventKey={4} title={t('auth.pages.welcome', {name: user.name})} id="personal-bar">
        <LinkContainer to={{pathname: '/dashboard'}}>
          <MenuItem eventKey={4.1}>{t('dashboard')}</MenuItem>
        </LinkContainer>
        <MenuItem divider />
        <MenuItem onClick={onSignOut} eventKey={4.2}>{t('auth.pages.sign-out')}</MenuItem>
      </NavDropdown>
    )
  }
})

Widget.propTypes = {
  user: PropTypes.object.isRequired,
  t: PropTypes.func.isRequired,
  onLoad: PropTypes.func.isRequired,
  onSignOut: PropTypes.func.isRequired
}

const Model = connect(
  state => ({user: state.currentUser}),
  dispatch => ({
    onLoad: function () {
      var token = window.sessionStorage.getItem('token')
      if (token) {
        dispatch(signIn(token))
      }
    },
    onSignOut: function () {
      dispatch(signOut())
    }
  })
)(Widget)

export default translate()(Model)
